[package]
name = "Back-End"
version = "0.0.1"
authors = ["jadson <jadson.g-matos@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"